# Generated by Django 4.2.5 on 2023-10-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_health_user_fitness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fitness',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gym_membership',
            new_name='employee',
        ),
    ]
