# Generated by Django 4.2.5 on 2023-10-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='')),
                ('job_title', models.CharField(max_length=100)),
                ('last_date', models.DateTimeField(auto_now=True, help_text='Enter last date and time for jobs')),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('job_category', models.ForeignKey(help_text='please select the job category', on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='jobs.jobcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
