# Generated by Django 4.2.5 on 2023-10-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedjobs',
            options={'verbose_name': 'Applied Jobs', 'verbose_name_plural': 'Applied Jobs'},
        ),
    ]
