# Generated by Django 4.2.5 on 2023-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_achivements_resume_eductaion_resume_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCompletionStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('resume', models.BooleanField(default=False)),
                ('screening_test', models.BooleanField(default=False)),
                ('video_test', models.BooleanField(default=False)),
                ('community', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
