# Generated by Django 4.2.5 on 2023-10-15 08:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_profilecompletionstar_resume_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='achivements',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='eductaion',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='extra_circulam_activity',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
